//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATABU_Barnabas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presence
    {
        public int IdPresence { get; set; }
        public System.DateTime DatePresence { get; set; }
        public System.TimeSpan HeureDebut { get; set; }
        public System.TimeSpan HeureFin { get; set; }
        public Nullable<int> idEtu { get; set; }
        public Nullable<int> IdCours { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Etudiant Etudiant { get; set; }
    }
}
